"""add playcounter and jokers allowed

Revision ID: 0bc8ed81835e
Revises: 5801411a5170
Create Date: 2020-05-06 18:21:29.612484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc8ed81835e'
down_revision = '5801411a5170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_games', sa.Column('joker', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('t_games', sa.Column('num_played', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_games', 'num_played')
    op.drop_column('t_games', 'joker')
    # ### end Alembic commands ###
