"""drop locale row in user

Revision ID: 0c677883ef5c
Revises: 54ca1f77281d
Create Date: 2020-04-16 16:35:31.391346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c677883ef5c'
down_revision = '54ca1f77281d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'locale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('locale', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
