"""create user table

Revision ID: 54ca1f77281d
Revises: 
Create Date: 2020-04-15 16:32:35.519592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ca1f77281d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('datecreated', sa.DateTime(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('flask_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_users_email'), 't_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_users_email'), table_name='t_users')
    op.drop_table('t_users')
    # ### end Alembic commands ###
