"""add player_id to game

Revision ID: 5801411a5170
Revises: 6b53ce909e7c
Create Date: 2020-04-17 12:43:27.621171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5801411a5170'
down_revision = '6b53ce909e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_games', sa.Column('player_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 't_games', 't_players', ['player_id'], ['player_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_games', type_='foreignkey')
    op.drop_column('t_games', 'player_id')
    # ### end Alembic commands ###
