"""create games, link_games, players table

Revision ID: 6b53ce909e7c
Revises: 0c677883ef5c
Create Date: 2020-04-16 17:10:00.106584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b53ce909e7c'
down_revision = '0c677883ef5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('user_game', sa.Boolean(), nullable=False),
    sa.Column('num_solved', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('club_img', sa.String(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('nationality_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_players_player_id'), 't_players', ['player_id'], unique=True)
    op.create_table('t_link_games_player',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['t_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['t_players.player_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uix_game_id_player_id_1')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_link_games_player')
    op.drop_index(op.f('ix_t_players_player_id'), table_name='t_players')
    op.drop_table('t_players')
    op.drop_table('t_games')
    # ### end Alembic commands ###
