from sqlalchemy.schema import CreateColumn
from sqlalchemy.ext.compiler import compiles

from app.models.user import User
from app.models.games import Game
from app.models.players import Player
from app.models.link_games_player import LinkGamePlayer


# To be able to use the identity feature
# https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#postgresql-10-identity-columns
@compiles(CreateColumn, "postgresql")
def use_identity(element, compiler, **kw):
    text = compiler.visit_create_column(element, **kw)
    text = text.replace("SERIAL", "INT GENERATED BY DEFAULT AS IDENTITY")
    return text
